In [4]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of the list_ variable and the array_list variable. The list_ variable is a Python list containing strings, while the array_list variable is a NumPy array. NumPy arrays have a specified data type for their elements.

In [6]:
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [7]:
# Print data types of elements in 'list_'
print("Data types of elements in 'list_':")
for item in list_:
    print(type(item))

# Print data types of elements in 'array_list'
print("\nData types of elements in 'array_list':")
for item in array_list:
    print(type(item))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [9]:
array_list = np.array(object = list_, dtype = int)
print("Data types of elements in 'list_':")
for item in list_:
    print(type(item))

# Print data types of elements in 'array_list'
print("\nData types of elements in 'array_list':")
for item in array_list:
    print(type(item))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [11]:
num_array.shape

(2, 3)

In [12]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [20]:
identity_mat = np.eye(5,5)
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# OR

In [17]:
data1=np.diag([1,1,1,1,1,])

In [18]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])